## Import the libraries

In [ ]:
import numpy as np

## Scalar

In [ ]:
s=5

## Vector

In [ ]:
v = np.array([5,-2,4]) #row vector
v

array([ 5, -2,  4])

## Matix 

In [ ]:
m = np.array([[5,12,6] , [-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [ ]:
type(s)

int

In [ ]:
type(v)
type(m)

numpy.ndarray

In [ ]:
s_array = np.array(5)
type(s_array)

numpy.ndarray

## Data shapes

In [ ]:
s_array.shape #0 dimension

()

In [ ]:
v.shape

(3,)

In [ ]:
m.shape


(2, 3)

## Creating column vector with reshape

In [ ]:
v.reshape(3,1) # column vector


array([[ 5],
       [-2],
       [ 4]])

In [ ]:
v.reshape(1,3) #row vector

array([[ 5, -2,  4]])

## Creating a tensor

In [ ]:
m2 = np.array([[9,16,10] , [3,4,5]])

In [ ]:
t = np.array([ m , m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9, 16, 10],
        [ 3,  4,  5]]])

In [ ]:
t.shape

(2, 2, 3)

## Manually creating a tensor

In [ ]:
t_manual = np.array([[[3,4,5],[6,7,8]] , [[3,4,5] , [5,6,7]]])
t_manual

array([[[3, 4, 5],
        [6, 7, 8]],

       [[3, 4, 5],
        [5, 6, 7]]])