## Import the libraries

In [1]:
import numpy as np

## Scalar

In [2]:
s=5

## Vector

In [3]:
v = np.array([5,-2,4]) #row vector
v

array([ 5, -2,  4])

## Matix 

In [4]:
m = np.array([[5,12,6] , [-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

## Data types

In [5]:
type(s)

int

In [6]:
type(v)
type(m)

numpy.ndarray

In [7]:
s_array = np.array(5)
type(s_array)

numpy.ndarray

## Data shapes

In [8]:
s_array.shape #0 dimension

()

In [9]:
v.shape

(3,)

In [10]:
m.shape


(2, 3)

## Creating column vector with reshape

In [11]:
v.reshape(3,1) # column vector


array([[ 5],
       [-2],
       [ 4]])

In [12]:
v.reshape(1,3) #row vector

array([[ 5, -2,  4]])

## Creating a tensor

In [13]:
m2 = np.array([[9,16,10] , [3,4,5]])

In [14]:
t = np.array([ m , m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9, 16, 10],
        [ 3,  4,  5]]])

In [15]:
t.shape

(2, 2, 3)

## Manually creating a tensor

In [16]:
t_manual = np.array([[[3,4,5],[6,7,8]] , [[3,4,5] , [5,6,7]]])
t_manual

array([[[3, 4, 5],
        [6, 7, 8]],

       [[3, 4, 5],
        [5, 6, 7]]])

##Transposing matrix

In [17]:
t_manual.T

array([[[3, 3],
        [6, 5]],

       [[4, 4],
        [7, 6]],

       [[5, 5],
        [8, 7]]])

## transposing vectors

In [18]:
v1 = np.array([1,2,3]) 

In [19]:
v1.T

array([1, 2, 3])

In [23]:
v1_reshaped = v1.reshape(1,3)
v1_reshaped

array([[1, 2, 3]])

In [24]:
v1_reshaped.T

array([[1],
       [2],
       [3]])